name: Run Pytest

on:
  push:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: bordercore
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
        ports:
          - 5432:5432
    env:
      PYTHONPATH: $PYTHONPATH:.:bordercore
      DJANGO_SETTINGS_MODULE: config.settings.dev
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        pip install -r requirements/dev.txt
        pip install pytest

    - name: Run mypy
      run: |
        mypy --config-file pyproject.toml \
          bordercore/accounts/ \
          bordercore/aws/ \
          bordercore/blob/ \
          bordercore/bookmark/ \
          bordercore/collection/ \
          bordercore/drill/ \
          bordercore/feed/ \
          bordercore/fitness/ \
          bordercore/lib/ \
          bordercore/node/ \
          bordercore/metrics/ \
          bordercore/music/ \
          bordercore/reminder/ \
          bordercore/search/ \
          bordercore/tag/ \
          bordercore/todo/

    - name: Run tests
      env:
        SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
        DJANGO_LOG_DIR: ${{ runner.temp }}
        DATABASE_HOST: localhost
        DATABASE_USER: postgres
        DATABASE_PASSWORD: postgres
      run: |
        pytest -m "not data_quality and not functional" ./bordercore/ -v
